# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 18:01
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('meas_models', '0001_initial'), ('meas_models', '0002_auto_20161123_2101'), ('meas_models', '0003_auto_20161124_1428'), ('meas_models', '0004_auto_20161124_1522'), ('meas_models', '0005_auto_20161130_1328'), ('meas_models', '0006_paper_subject'), ('meas_models', '0007_concept_order'), ('meas_models', '0008_formula'), ('meas_models', '0009_question_formulas'), ('meas_models', '0010_remove_question_source'), ('meas_models', '0011_auto_20170115_2135'), ('meas_models', '0012_formula_formula'), ('meas_models', '0013_auto_20170116_2251'), ('meas_models', '0014_auto_20170117_1646'), ('meas_models', '0015_auto_20170117_1721'), ('meas_models', '0016_auto_20170117_2325')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(choices=[(b'1', b'January'), (b'2', b'February'), (b'3', b'March'), (b'4', b'April'), (b'5', b'May'), (b'6', b'June'), (b'7', b'July'), (b'8', b'August'), (b'9', b'September'), (b'10', b'October'), (b'11', b'November'), (b'12', b'December')], default='1', max_length=20)),
                ('number', models.IntegerField()),
                ('no_of_question', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[(b'EX', b'Exam'), (b'PR', b'Practice')], default='EX', max_length=2)),
                ('source', models.CharField(choices=[(b'EP', b'Exam papers'), (b'OL', b'Online')], default='EP', max_length=2)),
                ('used_for', models.CharField(choices=[(b'NO', b'No'), (b'ON', b'Online'), (b'PA', b'Papers'), (b'BO', b'Both online and papers')], default='ON', max_length=2)),
                ('mark', models.IntegerField(default=1)),
                ('difficulty_level', models.CharField(choices=[(b'1', b'Very Easy'), (b'2', b'Easy'), (b'3', b'Average'), (b'4', b'Difficult'), (b'5', b'Very Difficult')], default='1', max_length=1)),
                ('respone_type', models.CharField(choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10)),
                ('content', ckeditor.fields.RichTextField()),
                ('solution', ckeditor.fields.RichTextField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Concept')),
                ('keypoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meas_models.KeyPoint')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meas_models.Paper')),
                ('answer', ckeditor.fields.RichTextField(default='Test')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.EducationLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('test_type', models.CharField(choices=[(b'PT', b'Practice Test'), (b'CT', b'Contest')], default=b'PT', max_length=200)),
                ('questions_list', models.TextField()),
                ('number_of_questions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Topic'),
        ),
        migrations.CreateModel(
            name='AnswerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=1)),
                ('part_content', ckeditor.fields.RichTextField()),
                ('part_respone_type', models.CharField(choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Question')),
                ('respone_type_1', models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True)),
                ('respone_type_2', models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True)),
                ('respone_type_3', models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True)),
                ('respone_type_4', models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True)),
                ('subpart_content_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subpart_content_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subpart_content_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subpart_content_4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('subpart_name_1', models.CharField(blank=True, max_length=10, null=True)),
                ('subpart_name_2', models.CharField(blank=True, max_length=10, null=True)),
                ('subpart_name_3', models.CharField(blank=True, max_length=10, null=True)),
                ('subpart_name_4', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meas_models.Subject'),
        ),
        migrations.AddField(
            model_name='concept',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('constant_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('inorder_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('sorted_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('status', models.BooleanField(default=False)),
                ('structure_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('variable_term', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='source',
        ),
        migrations.CreateModel(
            name='FormulaIndex',
            fields=[
                ('indexkey', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='index key')),
                ('docsids', models.TextField(blank=True, null=True)),
                ('df', models.PositiveIntegerField(blank=True, default=1, verbose_name='frequency')),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meas_models.Question'),
        ),
    ]
