# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 07:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import meas_models.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=200)),
                ('solution', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Proficiency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(max_length=1000)),
                ('respone_type', models.CharField(choices=[('Numberic', 'Exam Numberic'), ('Sketch', 'Sketch'), ('EXPRESSION', 'Expression'), ('Text', 'Text'), ('Prove', 'Prove')], default='Text', max_length=10)),
                ('is_subpart', models.BooleanField(default=0)),
                ('is_complete', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('source', models.CharField(choices=[('EP', 'Exam papers'), ('OL', 'Online')], default='EP', max_length=2)),
                ('difficulty_level', models.IntegerField(default=0, validators=[meas_models.models.validate_difficulty_range])),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.EducationLevel')),
            ],
        ),
        migrations.CreateModel(
            name='SubPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1000)),
                ('answer', models.TextField(max_length=200)),
                ('solution', models.TextField(max_length=1000)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Part')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('AP', 'Adaptive Test'), ('CT', 'Contest')], default='AP', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Question')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=1000)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='proficiency',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Test'),
        ),
        migrations.AddField(
            model_name='proficiency',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='part',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Question'),
        ),
        migrations.AddField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Topic'),
        ),
    ]
