# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0001_squashed_0016_auto_20170117_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='question',
        ),
    ]
