# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 06:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0002_auto_20161123_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1)),
                ('content', ckeditor.fields.RichTextField()),
                ('respone_type', models.CharField(choices=[(b'Numberic', b'Exam Numberic'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSubPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('content', ckeditor.fields.RichTextField()),
                ('respone_type', models.CharField(choices=[(b'Numberic', b'Exam Numberic'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10)),
                ('answer_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.AnswerPart')),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='answerpart',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meas_models.Question'),
        ),
    ]
