# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0003_formula_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaindex',
            name='idf',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
