# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 05:28
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0004_auto_20161124_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=ckeditor.fields.RichTextField(default='Test'),
        ),
        migrations.AlterField(
            model_name='answerpart',
            name='part_respone_type',
            field=models.CharField(choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='answerpart',
            name='respone_type_1',
            field=models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answerpart',
            name='respone_type_2',
            field=models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answerpart',
            name='respone_type_3',
            field=models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='answerpart',
            name='respone_type_4',
            field=models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='respone_type',
            field=models.CharField(choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10),
        ),
    ]
