# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 11:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0005_auto_20170118_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulaindex',
            name='idf',
        ),
    ]
