# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0005_auto_20161130_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='meas_models.Subject'),
        ),
    ]
