# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-12 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0008_formula'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='formulas',
            field=models.ManyToManyField(blank=True, null=True, to='meas_models.Formula'),
        ),
    ]
