# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-05 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0009_question_formulas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='source',
        ),
    ]
