# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0010_remove_question_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='constant_term',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='inorder_term',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='sorted_term',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='structure_term',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='formula',
            name='variable_term',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
