# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-15 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0011_auto_20170115_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='formula',
            name='formula',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
