# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0013_auto_20170116_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formula',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
