# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0014_auto_20170117_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaindex',
            name='docsids',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulaindex',
            name='indexkey',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='index key'),
        ),
    ]
