# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-17 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meas_models', '0015_auto_20170117_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='formulas',
        ),
        migrations.AddField(
            model_name='formula',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meas_models.Question'),
        ),
    ]
