const FORMULAS = {
    STRINGS_MAP: {
        'FORMULA_TITLE': ['STR_ALL_TITLE', 'STR_ARITH_TITLE',
            'STR_RELATION_TITLE', 'STR_SYMBOL_TITLE',
            'STR_ARROW_TITLE', 'STR_FUNCTION_TITLE',
            'STR_TRIG_TITLE', 'STR_EXP_TITLE',
        ],
        'STR_ARROW_TITLE': ['STR_ARROW_LEFT_ARROW',
            'STR_ARROW_LEFT_DOUBLEARROW',
            'STR_ARROW_RIGHT_ARROW',
            'STR_ARROW_RIGHT_DOUBLEARROW',
            'STR_ARROW_LEFTRIGHT_ARROW',
            'STR_ARROW_LEFTRIGHT_DOUBLEARROW'
        ],
        'FORMULA_ARROW': ['FORMULA_LEFT_ARROW',
            'FORMULA_LEFT_DOUBLEARROW',
            'FORMULA_RIGHT_ARROW',
            'FORMULA_RIGHT_DOUBLEARROW',
            'FORMULA_LEFTRIGHT_ARROW',
            'FORMULA_LEFTRIGHT_DOUBLEARROW'
        ],
        'STR_EXP_TITLE': ['STR_EXP_SQUARE', 'STR_EXP_SQRT',
            'STR_EXP_ROOT', 'STR_EXP_EPS', 'STR_EXP_SUB',
            'STR_EXP_LOG', 'STR_EXP_LOG_BASE',
            'STR_EXP_LN'
        ],
        'FORMULA_EXP': ['FORMULA_SQUARE', 'FORMULA_SQRT',
            'FORMULA_EXP_ROOT', 'FORMULA_EPS', 'FORMULA_SUB',
            'FORMULA_LOG', 'FORMULA_LOGBASE', 'FORMULA_LN'
        ],
        'STR_TRIG_TITLE': ['STR_TRIG_SIN', 'STR_TRIG_COS',
            'STR_TRIG_TAN', 'STR_TRIG_SEC',
            'STR_TRIG_COT', 'STR_TRIG_CSC'
        ],
        'FORMULA_TRIG': ['FORMULA_SIN', 'FORMULA_COS',
            'FORMULA_TAN', 'FORMULA_SEC',
            'FORMULA_COT', 'FORMULA_CSC'
        ],
        'STR_FUNCTION_TITLE': ['STR_FUNCTION_SUM', 'STR_FUNCTION_LIM',
            'STR_FUNCTION_INTEGRAL'
        ],
        'FORMULA_FUNCTION': ['FORMULA_SUM', 'FORMULA_LIM',
            'FORMULA_INTEGRAL'
        ],
        'STR_ARITH_TITLE': ['STR_ARITH_PLUS', 'STR_ARITH_MINUS',
            'STR_ARITH_MULTIPLY', 'STR_ARITH_DIVIDE',
            'STR_ARITH_FRACTION', 'STR_ARITH_EQUAL',
            'STR_ARITH_PM'
        ],
        'FORMULA_ARITH': ['FORMULA_PLUS', 'FORMULA_MINUS',
            'FORMULA_MULTIPLY', 'FORMULA_DIVIDE',
            'FORMULA_FRACTION', 'FORMULA_EQ',
            'FORMULA_PM'
        ],
        'STR_SYMBOL_TITLE': ['STR_SYMBOL_COMMA', 'STR_SYMBOL_SEMICOLON',
            'STR_SYMBOL_INFINITY', 'STR_SYMBOL_FORALL',
            'STR_SYMBOL_EXIST', 'STR_SYMBOL_NEGATION',
            'STR_SYMBOL_EMPTYSET', 'STR_SYMBOL_ANGLE',
            'STR_SYMBOL_DOT', 'STR_SYMBOL_PIPE'
        ],
        'FORMULA_SYMBOL': ['FORMULA_COMMA', 'FORMULA_SEMICOLON',
            'FORMULA_INFINITY', 'FORMULA_FORALL',
            'FORMULA_EXIST', 'FORMULA_NEGATION',
            'FORMULA_EMPTYSET', 'FORMULA_ANGLE',
            'FORMULA_DOT', 'FORMULA_PIPE'
        ],
        'STR_RELATION_TITLE': ['STR_REL_NEQ', 'STR_REL_LT', 'STR_REL_GT',
            'STR_REL_COLON', 'STR_REL_LEQ', 'STR_REL_GEQ',
            'STR_REL_CAP', 'STR_REL_CUP',
            'STR_REL_SUBSET', 'STR_REL_SUBSETEQ',
            'STR_REL_SUPSET', 'STR_REL_SUPSETEQ',
            'STR_REL_IN', 'STR_REL_EQUIV', 'STR_REL_APPROX'
        ],
        'FORMULA_RELATION': ['FORMULA_NEQ', 'FORMULA_LT', 'FORMULA_GT',
            'FORMULA_COLON', 'FORMULA_LEQ',
            'FORMULA_GEQ', 'FORMULA_CAP', 'FORMULA_CUP',
            'FORMULA_SUBSET', 'FORMULA_SUBSETEQ',
            'FORMULA_SUPSET', 'FORMULA_SUPSETEQ',
            'FORMULA_IN', 'FORMULA_EQUIV',
            'FORMULA_APPROX'
        ]
    },
    STRINGS: {
        'STR_ARROW_LEFTRIGHT_DOUBLEARROW': 'Double Left Right Arrow',
        'STR_REL_SUPSET': 'Superset of',
        'STR_ARROW_TITLE': 'Arrows',
        'STR_REL_SUBSETEQ': 'Subset Equal of',
        'STR_EXP_EPS': 'Exponent',
        'STR_FUNCTION_TITLE': 'Functions',
        'STR_REL_SUBSET': 'Subset of',
        'STR_REL_APPROX': 'Approximately',
        'STR_TRIG_SEC': 'Sec',
        'STR_TRIG_TAN': 'Tan',
        'STR_EXP_TITLE': 'Exponential (Power, Root, Log)',
        'STR_EXP_LOG': 'Log',
        'STR_SYMBOL_EMPTYSET': 'Empty Set',
        'STR_REL_NEQ': 'Not Equal',
        'STR_ARROW_RIGHT_DOUBLEARROW': 'Double Right Arrow',
        'STR_EXP_LN': 'Log Natural',
        'STR_RELATION_TITLE': 'Relations',
        'STR_EXP_LOG_BASE': 'Log Base',
        'STR_ARITH_MINUS': '- (Minus)',
        'STR_SYMBOL_EXIST': 'Exist',
        'STR_REL_SUPSETEQ': 'Superset Equal of',
        'STR_TRIG_SIN': 'Sin',
        'STR_FUNCTION_SUM': 'Sum',
        'STR_TRIG_COT': 'Cot',
        'STR_REL_GEQ': 'Greater Than or Equal to',
        'STR_ALL_TITLE': 'All',
        'STR_SYMBOL_COMMA': 'Comma',
        'STR_TRIG_COS': 'Cos',
        'STR_ARITH_EQUAL': '= (Equal)',
        'STR_SYMBOL_NEGATION': 'Negation',
        'STR_SYMBOL_FORALL': 'For All',
        'STR_ARROW_LEFTRIGHT_ARROW': 'Left Right Arrow',
        'STR_ARROW_LEFT_ARROW': 'Left Arrow',
        'STR_EXP_ROOT': 'Root',
        'STR_REL_LT': 'Less Than',
        'STR_REL_COLON': ': (Colon)',
        'STR_SYMBOL_DOT': 'Dot',
        'STR_REL_LEQ': 'Less Than or Equal to',
        'STR_ARROW_LEFT_DOUBLEARROW': 'Double Left Arrow',
        'STR_EXP_SQUARE': 'Square',
        'STR_REL_GT': 'Greater Than',
        'STR_SYMBOL_SEMICOLON': 'Semicolon',
        'STR_ARITH_MULTIPLY': '* (Multiply)',
        'STR_ARITH_PLUS': '+ (Plus)',
        'STR_SYMBOL_INFINITY': 'Infinity',
        'STR_ARITH_DIVIDE': '/ (Divide)',
        'STR_SYMBOL_TITLE': 'Symbols',
        'STR_EXP_SUB': 'Sub',
        'STR_REL_IN': 'In',
        'STR_SYMBOL_PIPE': 'Pipe, Or',
        'STR_ARITH_PM': 'Plus Minus',
        'STR_EXP_SQRT': 'Square Root',
        'STR_FUNCTION_INTEGRAL': 'Integral',
        'STR_SYMBOL_ANGLE': 'Angle',
        'STR_ARROW_RIGHT_ARROW': 'Right Arrow',
        'STR_TRIG_TITLE': 'Trigonometry',
        'STR_REL_EQUIV': 'Equivalent',
        'STR_ARITH_FRACTION': 'a/b (Fraction)',
        'STR_TRIG_CSC': 'Csc',
        'STR_FUNCTION_LIM': 'Limit',
        'STR_ARITH_TITLE': 'Arithmetics',
        'STR_REL_CAP': 'And / Intersection',
        'STR_REL_CUP': 'Or / Union',
    },
    LATEX_SYMBOLS: {
        'FORMULA_FORALL': '\\forall',
        'FORMULA_RIGHT_DOUBLEARROW': '\\Rightarrow',
        'FORMULA_SUB': 'x_{2}',
        'FORMULA_NEGATION': '\\neg',
        'FORMULA_GEQ': '\\geq',
        'FORMULA_SUBSETEQ': '\\subseteq',
        'FORMULA_LEFTRIGHT_ARROW': '\\leftrightarrow',
        'FORMULA_LEFT_ARROW': '\\leftarrow',
        'FORMULA_MULTIPLY': '\\times',
        'FORMULA_LT': '<',
        'FORMULA_EXP_ROOT': '\\sqrt[b]{a}',
        'FORMULA_LOGBASE': '\\log_b x',
        'FORMULA_LEFTRIGHT_DOUBLEARROW': '\\Leftrightarrow',
        'FORMULA_EMPTYSET': '\\emptyset',
        'FORMULA_SUBSET': '\\subset',
        'FORMULA_LIM': '\\lim_{x\\to\\infty}',
        'FORMULA_SUPSET': '\\supset',
        'FORMULA_CUP': '\\cup',
        'FORMULA_EPS': 'e^{x}',
        'FORMULA_CAP': '\\cap',
        'FORMULA_TAN': '\\tan x',
        'FORMULA_SQUARE': 'x^{2}',
        'FORMULA_SEC': '\\sec x',
        'FORMULA_EXIST': '\\exists',
        'FORMULA_RIGHT_ARROW': '\\rightarrow',
        'FORMULA_INTEGRAL': '\\int_{-1}^{1} xdx',
        'FORMULA_SUM': '\\sum_{i=0}^{n} {a}_{n}',
        'FORMULA_EQ': '=',
        'FORMULA_GT': '>',
        'FORMULA_NEQ': '\\neq',
        'FORMULA_PIPE': '|',
        'FORMULA_SQRT': '\\sqrt{x}',
        'FORMULA_LN': '\\ln x',
        'FORMULA_SIN': '\\sin x',
        'FORMULA_CSC': '\\csc x',
        'FORMULA_DOT': '.',
        'FORMULA_IN': '\\in',
        'FORMULA_COS': '\\cos x',
        'FORMULA_PM': '\\pm',
        'FORMULA_COT': '\\cot x',
        'FORMULA_LEFT_DOUBLEARROW': '\\Leftarrow',
        'FORMULA_FRACTION': '\\frac{x}{y}',
        'FORMULA_INFINITY': '\\infty',
        'FORMULA_MINUS': '-',
        'FORMULA_DIVIDE': '\\div',
        'FORMULA_PLUS': '+',
        'FORMULA_ANGLE': '\\angle',
        'FORMULA_APPROX': '\\approx',
        'FORMULA_LOG': '\\log x',
        'FORMULA_COMMA': ',',
        'FORMULA_EQUIV': '\\equiv',
        'FORMULA_SEMICOLON': ';',
        'FORMULA_COLON': ':',
        'FORMULA_LEQ': '\\leq',
        'FORMULA_SUPSETEQ': '\\supseteq'
    }
}

FORMULAS.STRINGS_MAP['STR_ALL_TITLE'] =
    FORMULAS.STRINGS_MAP['STR_ARITH_TITLE']
    .concat(FORMULAS.STRINGS_MAP['STR_RELATION_TITLE'])
    .concat(FORMULAS.STRINGS_MAP['STR_SYMBOL_TITLE'])
    .concat(FORMULAS.STRINGS_MAP['STR_ARROW_TITLE'])
    .concat(FORMULAS.STRINGS_MAP['STR_FUNCTION_TITLE'])
    .concat(FORMULAS.STRINGS_MAP['STR_TRIG_TITLE'])
    .concat(FORMULAS.STRINGS_MAP['STR_EXP_TITLE']);
FORMULAS.STRINGS_MAP['FORMULA_ALL'] =
    FORMULAS.STRINGS_MAP['FORMULA_ARITH']
    .concat(FORMULAS.STRINGS_MAP['FORMULA_RELATION'])
    .concat(FORMULAS.STRINGS_MAP['FORMULA_SYMBOL'])
    .concat(FORMULAS.STRINGS_MAP['FORMULA_ARROW'])
    .concat(FORMULAS.STRINGS_MAP['FORMULA_FUNCTION'])
    .concat(FORMULAS.STRINGS_MAP['FORMULA_TRIG'])
    .concat(FORMULAS.STRINGS_MAP['FORMULA_EXP']);


export default FORMULAS;