# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 17:23
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=1)),
                ('part_content', ckeditor.fields.RichTextField()),
                ('part_respone_type', models.CharField(choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10)),
                ('subpart_name_1', models.CharField(blank=True, max_length=10, null=True)),
                ('subpart_content_1', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('respone_type_1', models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True)),
                ('subpart_name_2', models.CharField(blank=True, max_length=10, null=True)),
                ('subpart_content_2', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('respone_type_2', models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True)),
                ('subpart_name_3', models.CharField(blank=True, max_length=10, null=True)),
                ('subpart_content_3', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('respone_type_3', models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True)),
                ('subpart_name_4', models.CharField(blank=True, max_length=10, null=True)),
                ('subpart_content_4', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('respone_type_4', models.CharField(blank=True, choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('inorder_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('sorted_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('structure_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('constant_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('variable_term', models.CharField(blank=True, max_length=1024, null=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='FormulaIndex',
            fields=[
                ('term_index', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='index key')),
                ('docsids', models.TextField(blank=True, null=True)),
                ('df', models.PositiveIntegerField(blank=True, default=1, verbose_name='frequency')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qa', models.TextField(null=True)),
                ('imagepath', models.FileField(upload_to='/static/image/')),
            ],
        ),
        migrations.CreateModel(
            name='KeyPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('keypoint_type', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.CharField(choices=[(b'1', b'January'), (b'2', b'February'), (b'3', b'March'), (b'4', b'April'), (b'5', b'May'), (b'6', b'June'), (b'7', b'July'), (b'8', b'August'), (b'9', b'September'), (b'10', b'October'), (b'11', b'November'), (b'12', b'December')], default='1', max_length=20)),
                ('number', models.IntegerField()),
                ('no_of_question', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paperset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True, verbose_name='title')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('question_type', models.CharField(blank=True, choices=[(b'EX', b'Exam'), (b'PR', b'Practice')], default='EX', max_length=2)),
                ('used_for', models.CharField(blank=True, choices=[(b'NO', b'No'), (b'ON', b'Online'), (b'PA', b'Papers'), (b'BO', b'Both online and papers')], default='ON', max_length=2)),
                ('marks', models.IntegerField(default=1)),
                ('difficulty_level', models.CharField(choices=[(b'1', b'Very Easy'), (b'2', b'Easy'), (b'3', b'Average'), (b'4', b'Difficult'), (b'5', b'Very Difficult')], default='1', max_length=1)),
                ('response_type', models.CharField(choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10)),
                ('source', models.TextField(verbose_name='source')),
                ('content', models.TextField()),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Concept')),
                ('keypoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.KeyPoint')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Paper')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('education_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.EducationLevel')),
            ],
        ),
        migrations.CreateModel(
            name='Subtopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(null=True)),
                ('concept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Concept')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('topic_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Subject')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subtopic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Subtopic'),
        ),
        migrations.AddField(
            model_name='paperset',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Subject'),
        ),
        migrations.AddField(
            model_name='paper',
            name='paperset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Paperset'),
        ),
        migrations.AddField(
            model_name='paper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Subject'),
        ),
        migrations.AddField(
            model_name='image',
            name='qa_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Question'),
        ),
        migrations.AddField(
            model_name='formula',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Question'),
        ),
        migrations.AddField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Topic'),
        ),
        migrations.AddField(
            model_name='answerpart',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv2.Question'),
        ),
    ]
