# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic_subject',
            new_name='subject',
        ),
    ]
