# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-15 02:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('apiv2', '0002_Formula_manytomany_in_formula_index'), ('apiv2', '0003_Remove_docsids_in_formulaindex')]

    dependencies = [
        ('apiv2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formulaindex',
            name='formulas',
            field=models.ManyToManyField(to=b'apiv2.Formula'),
        ),
        migrations.RemoveField(
            model_name='formulaindex',
            name='docsids',
        ),
    ]
