# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 00:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0003_auto_20170124_0819'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subtopic',
            new_name='Subconcept',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='subtopic',
            new_name='subconcept',
        ),
    ]
