# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 00:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0004_auto_20170124_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subconcept',
            old_name='title',
            new_name='name',
        ),
    ]
