# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0005_auto_20170124_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='keypoint',
        ),
        migrations.AddField(
            model_name='question',
            name='keypoints',
            field=models.ManyToManyField(to='apiv2.KeyPoint'),
        ),
        migrations.AddField(
            model_name='question',
            name='keywords',
            field=models.ManyToManyField(to='apiv2.Keywords'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subconcept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Subconcept'),
        ),
    ]
