# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 00:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0006_auto_20170124_0845'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keywords',
            new_name='Keyword',
        ),
    ]
