# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0008_auto_20170124_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulaindex',
            name='term_index',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
