# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0009_auto_20170124_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='month',
            field=models.CharField(max_length=64),
        ),
    ]
