# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0011_auto_20170124_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_sample',
            field=models.BooleanField(default=False),
        ),
    ]
