# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-24 03:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0012_question_is_sample'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keypoint',
            old_name='keypoint_type',
            new_name='type',
        ),
    ]
