# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0014_auto_20170125_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('inorder_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('sorted_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('structure_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('constant_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('variable_term', models.TextField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestFormulaIndexq',
            fields=[
                ('term_index', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('docsids', models.TextField(blank=True, null=True)),
                ('df', models.PositiveIntegerField(blank=True, default=1, verbose_name='frequency')),
            ],
        ),
        migrations.AlterField(
            model_name='concept',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='apiv2.Topic'),
        ),
        migrations.AlterField(
            model_name='keypoint',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keypoints', to='apiv2.Concept'),
        ),
        migrations.AlterField(
            model_name='paperset',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='papersets', to='apiv2.Subject'),
        ),
        migrations.AlterField(
            model_name='question',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='apiv2.Concept'),
        ),
        migrations.AlterField(
            model_name='question',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='apiv2.Paper'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subconcept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='apiv2.Subconcept'),
        ),
        migrations.AlterField(
            model_name='subconcept',
            name='concept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subconcepts', to='apiv2.Concept'),
        ),
        migrations.AddField(
            model_name='testformula',
            name='concept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Concept'),
        ),
        migrations.AddField(
            model_name='testformula',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.Question'),
        ),
    ]
