# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0015_auto_20170220_2355'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestFormulaIndexq',
            new_name='TestFormulaIndex',
        ),
    ]
