# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-20 23:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0016_auto_20170220_2356'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('question_type', models.CharField(blank=True, choices=[(b'EX', b'Exam'), (b'PR', b'Practice')], default='EX', max_length=2)),
                ('used_for', models.CharField(blank=True, choices=[(b'NO', b'No'), (b'ON', b'Online'), (b'PA', b'Papers'), (b'BO', b'Both online and papers')], default='ON', max_length=2)),
                ('marks', models.IntegerField(default=1)),
                ('difficulty_level', models.CharField(choices=[(b'1', b'Very Easy'), (b'2', b'Easy'), (b'3', b'Easy'), (b'4', b'Average'), (b'5', b'Average'), (b'6', b'Average'), (b'7', b'Difficult'), (b'8', b'Difficult'), (b'9', b'Very Difficult'), (b'10', b'Very Difficult')], default='1', max_length=2)),
                ('response_type', models.CharField(choices=[(b'Numberic', b'Numbers'), (b'Sketch', b'Sketch'), (b'EXPRESSION', b'Expression'), (b'Text', b'Text'), (b'Prove', b'Prove')], default=b'Text', max_length=10)),
                ('source', models.TextField()),
                ('content', models.TextField()),
                ('is_sample', models.BooleanField(default=False)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='apiv2.Concept')),
                ('keypoints', models.ManyToManyField(to='apiv2.KeyPoint')),
                ('keywords', models.ManyToManyField(to='apiv2.Keyword')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='apiv2.Paper')),
                ('subconcept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_questions', to='apiv2.Subconcept')),
            ],
        ),
        migrations.AlterField(
            model_name='testformula',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apiv2.TestQuestion'),
        ),
    ]
