# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-21 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0017_auto_20170221_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='testquestion',
            name='category',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
