# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0018_testquestion_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFormulaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='testformula',
            name='concept',
        ),
        migrations.AddField(
            model_name='testformula',
            name='categories',
            field=models.ManyToManyField(to='apiv2.TestFormulaCategory'),
        ),
    ]
