# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0019_auto_20170224_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testformulacategory',
            name='id',
        ),
        migrations.AlterField(
            model_name='testformulacategory',
            name='name',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
