# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0020_auto_20170224_1751'),
        ('apiv2', '0019_auto_20170224_2110'),
    ]

    operations = [
    ]
