# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0021_merge_20170224_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testformula',
            name='categories',
        ),
    ]
