# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0022_remove_testformula_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='testformula',
            name='categories',
            field=models.ManyToManyField(to='apiv2.TestFormulaCategory'),
        ),
    ]
