# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0023_testformula_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testformula',
            name='content',
            field=models.TextField(unique=True),
        ),
        migrations.RemoveField(
            model_name='testformula',
            name='question',
        ),
        migrations.AddField(
            model_name='testformula',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='apiv2.TestQuestion'),
        ),
    ]
