# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-24 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0024_auto_20170225_0709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testformula',
            name='content',
            field=models.TextField(max_length=512, unique=True),
        ),
    ]
