# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0026_auto_20170225_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testformula',
            name='question',
        ),
        migrations.AddField(
            model_name='testformula',
            name='question',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
