# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0027_auto_20170225_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testformula',
            name='categories',
        ),
        migrations.DeleteModel(
            name='TestFormula',
        ),
    ]
