# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-25 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0028_auto_20170225_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFormula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=1024)),
                ('status', models.BooleanField(default=False)),
                ('inorder_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('sorted_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('structure_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('constant_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('variable_term', models.TextField(blank=True, max_length=1024, null=True)),
                ('question', models.TextField(blank=True, max_length=1024, null=True)),
                ('categories', models.ManyToManyField(to='apiv2.TestFormulaCategory')),
            ],
        ),
    ]
