# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-03 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0031_questiontext'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questiontext',
            old_name='question_id',
            new_name='question',
        ),
    ]
