# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0033_auto_20170306_1858'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='categories',
            field=models.ManyToManyField(to='apiv2.FormulaCategory'),
        ),
    ]
