# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 11:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0034_auto_20170306_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formula',
            name='categories',
        ),
        migrations.DeleteModel(
            name='FormulaCategory',
        ),
    ]
