# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0035_auto_20170306_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormulaCategory',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='formula',
            name='categories',
            field=models.ManyToManyField(to='apiv2.FormulaCategory'),
        ),
    ]
