# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-08 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0036_auto_20170306_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='content_cleaned_text',
            field=models.TextField(blank=True),
        ),
    ]
