# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-12 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv2', '0037_question_content_cleaned_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='formula_categories',
            field=models.ManyToManyField(to='apiv2.FormulaCategory'),
        ),
    ]
